# Generated by Django 5.0.2 on 2024-02-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_tag_project_project_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.tag')),
            ],
        ),
    ]
